weights: ''
cfg: ./models/yolov4-csp.cfg
data: ./data/huansheng_el_2.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 2
img_size:
- 1600
- 1600
rect: false
resume: false
nosave: false
notest: true
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
name: yolov4-csp
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: 1
logdir: runs/
test_step: 300
total_batch_size: 4
world_size: 2
global_rank: 1
